"""Pydantic schemas for the GitHub notifications inbox pipeline.

One BaseModel per distinct structured output. Per KB5 (schema priming), each
distinct schema is produced in its own ``start_session()`` in ``pipeline.py``.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class ItemRender(BaseModel):
    """Free-form rendered prose for a single inbox item (elem_018, GENERATE).

    Only the natural-language fields are generated by the model; the surrounding
    Org-mode scaffolding (heading, :PROPERTIES: drawer, metadata table) is
    assembled deterministically in ``pipeline.py:render_item_subtree``.
    """

    summary: str = Field(
        description="A 2-3 sentence summary of the issue/PR giving enough context to act without clicking through.",
    )
    why_seeing: str = Field(
        description="One human-readable line explaining why the user is seeing this (the 'Why you're seeing this' line).",
    )
    latest_activity: str = Field(
        description="One line describing the most recent activity: who did what, with a brief excerpt if useful (1-2 sentences max).",
    )


class RunSummary(BaseModel):
    """Conversational end-of-run summary (elem_026, GENERATE)."""

    headline: str = Field(
        description="A short conversational sentence summarising what changed this run.",
    )
    new_count: int = Field(description="How many brand-new items were added to the inbox.")
    refreshed_count: int = Field(description="How many existing items were regenerated due to new activity.")
    carried_over_count: int = Field(description="How many existing items were carried over untouched.")
    most_important: str = Field(
        description="The most important Action Required item(s), or a note that there are none.",
    )
    reminder: str = Field(
        description="A reminder that items stay in the inbox until removed by hand from the inbox doc (~/org/github.org by default).",
    )


# Filter mode produced by the classify_filter_mode slot (elem_006). Defined here
# as the canonical Literal so pipeline.py and main.py share one definition.
FilterMode = Literal["all", "issues", "prs", "review_requests"]

# Inbox bucket produced by the classify_bucket slot (elem_017).
Bucket = Literal["action_required", "should_check", "fyi"]
